---
title: "AinB Group Assignment"
author: "Nikhita Venkatesan"
date: "12 December 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(stargazer)
library(ggplot2)
library(MASS)
library(grid)
library(gridExtra)
library(MASS)
library(AER)
```

```{r, echo = FALSE}
peoplepicking <- read.csv("peoplepickinganonymised.csv")
```

```{r, echo = FALSE}
friend <- peoplepicking[,4:63]
advice <- peoplepicking[,64:123]
creativity <- peoplepicking[,124:183]
implementation <- peoplepicking[,184:243]
influence <- peoplepicking[,244:303]
```

```{r, echo=FALSE}
friendmat <- as.matrix(friend)
advicemat <- as.matrix(advice)
creativitymat <- as.matrix(creativity)
implemat <- as.matrix(implementation)
influencemat <- as.matrix(influence)
```

```{r, echo = FALSE}
GraphFS <- graph_from_adjacency_matrix(friendmat, mode = "directed",add.colnames = TRUE, diag=FALSE)

degreeFS <- degree(GraphFS, mode="in")
```

```{r, echo = FALSE}
GraphCR <- graph_from_adjacency_matrix(creativitymat, mode = "directed",add.colnames = TRUE, diag=FALSE)

degreeCR <- degree(GraphCR, mode="in")
```

```{r, echo = FALSE}
GraphIM <- graph_from_adjacency_matrix(implemat, mode = "directed",add.colnames = TRUE, diag=FALSE)

degreeIM <- degree(GraphIM, mode="in")
```

```{r, echo = FALSE}
GraphIN <- graph_from_adjacency_matrix(influencemat, mode = "directed",add.colnames = TRUE, diag=FALSE)

degreeIN <- degree(GraphIN, mode="in")
```

# Regression Model Analysis

Model 1: Friendship v/s Creativity

```{r, echo = FALSE, results = 'asis'}
fsCR <- lm(degreeCR ~ degreeFS)

fsCR.lpm <- glm(degreeCR ~ degreeFS, family = "gaussian")

fsCR.poi <- glm(degreeCR ~ degreeFS, family = "poisson"(link = "log"))

fsCR.nb <- glm.nb(degreeCR ~ degreeFS)

stargazer(list(fsCR.lpm, fsCR.poi, fsCR.nb), type = "html", digits = 2)
```
\newline

Model 2: Friendship v/s Implementation

```{r, echo = FALSE, results = 'asis'}
fsIM <- lm(degreeIM ~ degreeFS)

fsIM.lpm <- glm(degreeIM ~ degreeFS, family = "gaussian")

fsIM.poi <- glm(degreeIM ~ degreeFS, family = "poisson"(link = "log"))

fsIM.nb <- glm.nb(degreeIM ~ degreeFS)

stargazer(list(fsIM.lpm, fsIM.poi, fsIM.nb), type = "html", digits = 2)
```
\newline

Model 3: Friendship v/s Influence
```{r, echo = FALSE, results = 'asis'}
fsIN <- lm(degreeIN ~ degreeFS)

fsIN.lpm <- glm(degreeIN ~ degreeFS, family = "gaussian")

fsIN.poi <- glm(degreeIN ~ degreeFS, family = "poisson"(link = "log"))

fsIN.nb <- glm.nb(degreeIN ~ degreeFS)

stargazer(list(fsIN.lpm, fsIN.poi, fsIN.nb), type = "html", digits = 2)
```
\newline

```{r, echo = FALSE}
friendship <- ggplot() + geom_density(aes(x = degreeFS))
creativity <- ggplot() + geom_density(aes(x = degreeCR))
implementation <- ggplot() + geom_density(aes(x = degreeIM))
influence <- ggplot() + geom_density(aes(x = degreeIN))
```
\newline

```{r, echo = FALSE}
multiplot <- function(..., plotlist = NULL, file, cols = 1, layout = NULL) {
  require(grid)

  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  if (is.null(layout)) {
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                 ncol = cols, nrow = ceiling(numPlots/cols))
}

if (numPlots == 1) {
print(plots[[1]])

} else {
grid.newpage()
pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

for (i in 1:numPlots) {
  matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

  print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                  layout.pos.col = matchidx$col))
 }
}
 }
```

```{r, echo = FALSE}
multiplot(friendship, creativity, implementation, influence, cols=2)
```

```{r, echo = FALSE}
summary(fsCR.poi)
summary(fsCR.nb)

summary(fsIM.poi)
summary(fsIM.nb)

summary(fsIN.poi)
summary(fsIN.nb)
```


```{r, echo = FALSE}
dispersiontest(fsCR.poi, trafo = 1)
dispersiontest(fsIM.poi, trafo = 1)
dispersiontest(fsIN.poi, trafo = 1)
```

